[package]
name = "rgbe"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2.19"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"

[dependencies.sdl2]
version = "0.36"
